# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'karel10x10.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1228, 891)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 20, 1211, 841))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout_7 = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.pushButton_31 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_31.setObjectName(_fromUtf8("pushButton_31"))
        self.gridLayout_5.addWidget(self.pushButton_31, 0, 3, 1, 1)
        self.pushButton_21 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_21.setObjectName(_fromUtf8("pushButton_21"))
        self.gridLayout_5.addWidget(self.pushButton_21, 2, 1, 1, 1)
        self.pushButton_22 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_22.setObjectName(_fromUtf8("pushButton_22"))
        self.gridLayout_5.addWidget(self.pushButton_22, 0, 1, 1, 1)
        self.pushButton_25 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_25.setObjectName(_fromUtf8("pushButton_25"))
        self.gridLayout_5.addWidget(self.pushButton_25, 3, 1, 1, 1)
        self.pushButton_23 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_23.setObjectName(_fromUtf8("pushButton_23"))
        self.gridLayout_5.addWidget(self.pushButton_23, 2, 3, 1, 1)
        self.pushButton_26 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_26.setObjectName(_fromUtf8("pushButton_26"))
        self.gridLayout_5.addWidget(self.pushButton_26, 0, 0, 1, 1)
        self.pushButton_24 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_24.setObjectName(_fromUtf8("pushButton_24"))
        self.gridLayout_5.addWidget(self.pushButton_24, 0, 2, 1, 1)
        self.pushButton_27 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_27.setObjectName(_fromUtf8("pushButton_27"))
        self.gridLayout_5.addWidget(self.pushButton_27, 1, 0, 1, 1)
        self.pushButton_30 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_30.setObjectName(_fromUtf8("pushButton_30"))
        self.gridLayout_5.addWidget(self.pushButton_30, 4, 2, 1, 1)
        self.pushButton_28 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_28.setObjectName(_fromUtf8("pushButton_28"))
        self.gridLayout_5.addWidget(self.pushButton_28, 3, 0, 1, 1)
        self.pushButton_29 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_29.setObjectName(_fromUtf8("pushButton_29"))
        self.gridLayout_5.addWidget(self.pushButton_29, 2, 0, 1, 1)
        self.pushButton_34 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_34.setObjectName(_fromUtf8("pushButton_34"))
        self.gridLayout_5.addWidget(self.pushButton_34, 3, 2, 1, 1)
        self.pushButton_32 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_32.setObjectName(_fromUtf8("pushButton_32"))
        self.gridLayout_5.addWidget(self.pushButton_32, 1, 3, 1, 1)
        self.pushButton_33 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_33.setObjectName(_fromUtf8("pushButton_33"))
        self.gridLayout_5.addWidget(self.pushButton_33, 2, 2, 1, 1)
        self.pushButton_35 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_35.setObjectName(_fromUtf8("pushButton_35"))
        self.gridLayout_5.addWidget(self.pushButton_35, 3, 3, 1, 1)
        self.pushButton_37 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_37.setObjectName(_fromUtf8("pushButton_37"))
        self.gridLayout_5.addWidget(self.pushButton_37, 1, 2, 1, 1)
        self.pushButton_38 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_38.setObjectName(_fromUtf8("pushButton_38"))
        self.gridLayout_5.addWidget(self.pushButton_38, 1, 1, 1, 1)
        self.pushButton_36 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_36.setObjectName(_fromUtf8("pushButton_36"))
        self.gridLayout_5.addWidget(self.pushButton_36, 4, 1, 1, 1)
        self.pushButton_39 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_39.setObjectName(_fromUtf8("pushButton_39"))
        self.gridLayout_5.addWidget(self.pushButton_39, 4, 0, 1, 1)
        self.pushButton_40 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_40.setObjectName(_fromUtf8("pushButton_40"))
        self.gridLayout_5.addWidget(self.pushButton_40, 4, 3, 1, 1)
        self.pushButton_130 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_130.setObjectName(_fromUtf8("pushButton_130"))
        self.gridLayout_5.addWidget(self.pushButton_130, 5, 1, 1, 1)
        self.pushButton_77 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_77.setObjectName(_fromUtf8("pushButton_77"))
        self.gridLayout_5.addWidget(self.pushButton_77, 5, 7, 1, 1)
        self.pushButton_76 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_76.setObjectName(_fromUtf8("pushButton_76"))
        self.gridLayout_5.addWidget(self.pushButton_76, 5, 8, 1, 1)
        self.pushButton_127 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_127.setObjectName(_fromUtf8("pushButton_127"))
        self.gridLayout_5.addWidget(self.pushButton_127, 5, 5, 1, 1)
        self.pushButton_79 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_79.setObjectName(_fromUtf8("pushButton_79"))
        self.gridLayout_5.addWidget(self.pushButton_79, 5, 6, 1, 1)
        self.pushButton_129 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_129.setObjectName(_fromUtf8("pushButton_129"))
        self.gridLayout_5.addWidget(self.pushButton_129, 5, 9, 1, 1)
        self.pushButton_78 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_78.setObjectName(_fromUtf8("pushButton_78"))
        self.gridLayout_5.addWidget(self.pushButton_78, 5, 2, 1, 1)
        self.pushButton_128 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_128.setObjectName(_fromUtf8("pushButton_128"))
        self.gridLayout_5.addWidget(self.pushButton_128, 5, 3, 1, 1)
        self.pushButton_126 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_126.setObjectName(_fromUtf8("pushButton_126"))
        self.gridLayout_5.addWidget(self.pushButton_126, 5, 4, 1, 1)
        self.pushButton_132 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_132.setObjectName(_fromUtf8("pushButton_132"))
        self.gridLayout_5.addWidget(self.pushButton_132, 6, 7, 1, 1)
        self.pushButton_133 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_133.setObjectName(_fromUtf8("pushButton_133"))
        self.gridLayout_5.addWidget(self.pushButton_133, 6, 3, 1, 1)
        self.pushButton_135 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_135.setObjectName(_fromUtf8("pushButton_135"))
        self.gridLayout_5.addWidget(self.pushButton_135, 6, 4, 1, 1)
        self.pushButton_131 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_131.setObjectName(_fromUtf8("pushButton_131"))
        self.gridLayout_5.addWidget(self.pushButton_131, 6, 5, 1, 1)
        self.pushButton_138 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_138.setObjectName(_fromUtf8("pushButton_138"))
        self.gridLayout_5.addWidget(self.pushButton_138, 6, 6, 1, 1)
        self.pushButton_136 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_136.setObjectName(_fromUtf8("pushButton_136"))
        self.gridLayout_5.addWidget(self.pushButton_136, 6, 8, 1, 1)
        self.pushButton_137 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_137.setObjectName(_fromUtf8("pushButton_137"))
        self.gridLayout_5.addWidget(self.pushButton_137, 6, 9, 1, 1)
        self.pushButton_61 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_61.setObjectName(_fromUtf8("pushButton_61"))
        self.gridLayout_5.addWidget(self.pushButton_61, 3, 5, 1, 1)
        self.pushButton_56 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_56.setObjectName(_fromUtf8("pushButton_56"))
        self.gridLayout_5.addWidget(self.pushButton_56, 2, 5, 1, 1)
        self.pushButton_66 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_66.setObjectName(_fromUtf8("pushButton_66"))
        self.gridLayout_5.addWidget(self.pushButton_66, 4, 5, 1, 1)
        self.pushButton_51 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_51.setObjectName(_fromUtf8("pushButton_51"))
        self.gridLayout_5.addWidget(self.pushButton_51, 1, 5, 1, 1)
        self.pushButton_143 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_143.setObjectName(_fromUtf8("pushButton_143"))
        self.gridLayout_5.addWidget(self.pushButton_143, 7, 5, 1, 1)
        self.pushButton_144 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_144.setObjectName(_fromUtf8("pushButton_144"))
        self.gridLayout_5.addWidget(self.pushButton_144, 7, 4, 1, 1)
        self.pushButton_146 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_146.setObjectName(_fromUtf8("pushButton_146"))
        self.gridLayout_5.addWidget(self.pushButton_146, 7, 2, 1, 1)
        self.pushButton_148 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_148.setObjectName(_fromUtf8("pushButton_148"))
        self.gridLayout_5.addWidget(self.pushButton_148, 7, 1, 1, 1)
        self.pushButton_147 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_147.setObjectName(_fromUtf8("pushButton_147"))
        self.gridLayout_5.addWidget(self.pushButton_147, 7, 3, 1, 1)
        self.pushButton_140 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_140.setObjectName(_fromUtf8("pushButton_140"))
        self.gridLayout_5.addWidget(self.pushButton_140, 7, 7, 1, 1)
        self.pushButton_71 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_71.setObjectName(_fromUtf8("pushButton_71"))
        self.gridLayout_5.addWidget(self.pushButton_71, 7, 0, 1, 1)
        self.pushButton_75 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_75.setObjectName(_fromUtf8("pushButton_75"))
        self.gridLayout_5.addWidget(self.pushButton_75, 9, 0, 1, 1)
        self.pushButton_72 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_72.setObjectName(_fromUtf8("pushButton_72"))
        self.gridLayout_5.addWidget(self.pushButton_72, 8, 0, 1, 1)
        self.pushButton_145 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_145.setObjectName(_fromUtf8("pushButton_145"))
        self.gridLayout_5.addWidget(self.pushButton_145, 7, 6, 1, 1)
        self.pushButton_74 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_74.setObjectName(_fromUtf8("pushButton_74"))
        self.gridLayout_5.addWidget(self.pushButton_74, 5, 0, 1, 1)
        self.pushButton_73 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_73.setObjectName(_fromUtf8("pushButton_73"))
        self.gridLayout_5.addWidget(self.pushButton_73, 6, 0, 1, 1)
        self.pushButton_141 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_141.setObjectName(_fromUtf8("pushButton_141"))
        self.gridLayout_5.addWidget(self.pushButton_141, 7, 8, 1, 1)
        self.pushButton_142 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_142.setObjectName(_fromUtf8("pushButton_142"))
        self.gridLayout_5.addWidget(self.pushButton_142, 7, 9, 1, 1)
        self.pushButton_42 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_42.setObjectName(_fromUtf8("pushButton_42"))
        self.gridLayout_5.addWidget(self.pushButton_42, 0, 5, 1, 1)
        self.pushButton_54 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_54.setObjectName(_fromUtf8("pushButton_54"))
        self.gridLayout_5.addWidget(self.pushButton_54, 2, 8, 1, 1)
        self.pushButton_49 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_49.setObjectName(_fromUtf8("pushButton_49"))
        self.gridLayout_5.addWidget(self.pushButton_49, 1, 6, 1, 1)
        self.pushButton_55 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_55.setObjectName(_fromUtf8("pushButton_55"))
        self.gridLayout_5.addWidget(self.pushButton_55, 2, 6, 1, 1)
        self.pushButton_48 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_48.setObjectName(_fromUtf8("pushButton_48"))
        self.gridLayout_5.addWidget(self.pushButton_48, 1, 7, 1, 1)
        self.pushButton_45 = QtGui.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_45.sizePolicy().hasHeightForWidth())
        self.pushButton_45.setSizePolicy(sizePolicy)
        self.pushButton_45.setObjectName(_fromUtf8("pushButton_45"))
        self.gridLayout_5.addWidget(self.pushButton_45, 0, 8, 1, 1)
        self.pushButton_53 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_53.setObjectName(_fromUtf8("pushButton_53"))
        self.gridLayout_5.addWidget(self.pushButton_53, 2, 7, 1, 1)
        self.pushButton_41 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_41.setObjectName(_fromUtf8("pushButton_41"))
        self.gridLayout_5.addWidget(self.pushButton_41, 0, 4, 1, 1)
        self.pushButton_44 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_44.setObjectName(_fromUtf8("pushButton_44"))
        self.gridLayout_5.addWidget(self.pushButton_44, 0, 7, 1, 1)
        self.pushButton_52 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_52.setObjectName(_fromUtf8("pushButton_52"))
        self.gridLayout_5.addWidget(self.pushButton_52, 2, 9, 1, 1)
        self.pushButton_43 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_43.setObjectName(_fromUtf8("pushButton_43"))
        self.gridLayout_5.addWidget(self.pushButton_43, 0, 6, 1, 1)
        self.pushButton_59 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_59.setObjectName(_fromUtf8("pushButton_59"))
        self.gridLayout_5.addWidget(self.pushButton_59, 3, 9, 1, 1)
        self.pushButton_64 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_64.setObjectName(_fromUtf8("pushButton_64"))
        self.gridLayout_5.addWidget(self.pushButton_64, 4, 8, 1, 1)
        self.pushButton_63 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_63.setObjectName(_fromUtf8("pushButton_63"))
        self.gridLayout_5.addWidget(self.pushButton_63, 4, 7, 1, 1)
        self.pushButton_68 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_68.setObjectName(_fromUtf8("pushButton_68"))
        self.gridLayout_5.addWidget(self.pushButton_68, 2, 4, 1, 1)
        self.pushButton_67 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_67.setObjectName(_fromUtf8("pushButton_67"))
        self.gridLayout_5.addWidget(self.pushButton_67, 1, 4, 1, 1)
        self.pushButton_50 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_50.setObjectName(_fromUtf8("pushButton_50"))
        self.gridLayout_5.addWidget(self.pushButton_50, 1, 9, 1, 1)
        self.pushButton_47 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_47.setObjectName(_fromUtf8("pushButton_47"))
        self.gridLayout_5.addWidget(self.pushButton_47, 1, 8, 1, 1)
        self.pushButton_69 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_69.setObjectName(_fromUtf8("pushButton_69"))
        self.gridLayout_5.addWidget(self.pushButton_69, 3, 4, 1, 1)
        self.pushButton_58 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_58.setObjectName(_fromUtf8("pushButton_58"))
        self.gridLayout_5.addWidget(self.pushButton_58, 3, 6, 1, 1)
        self.pushButton_57 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_57.setObjectName(_fromUtf8("pushButton_57"))
        self.gridLayout_5.addWidget(self.pushButton_57, 3, 8, 1, 1)
        self.pushButton_65 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_65.setObjectName(_fromUtf8("pushButton_65"))
        self.gridLayout_5.addWidget(self.pushButton_65, 4, 6, 1, 1)
        self.pushButton_60 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_60.setObjectName(_fromUtf8("pushButton_60"))
        self.gridLayout_5.addWidget(self.pushButton_60, 3, 7, 1, 1)
        self.pushButton_70 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_70.setObjectName(_fromUtf8("pushButton_70"))
        self.gridLayout_5.addWidget(self.pushButton_70, 4, 4, 1, 1)
        self.pushButton_139 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_139.setObjectName(_fromUtf8("pushButton_139"))
        self.gridLayout_5.addWidget(self.pushButton_139, 6, 1, 1, 1)
        self.pushButton_134 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_134.setObjectName(_fromUtf8("pushButton_134"))
        self.gridLayout_5.addWidget(self.pushButton_134, 6, 2, 1, 1)
        self.pushButton_62 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_62.setObjectName(_fromUtf8("pushButton_62"))
        self.gridLayout_5.addWidget(self.pushButton_62, 4, 9, 1, 1)
        self.pushButton_46 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_46.setObjectName(_fromUtf8("pushButton_46"))
        self.gridLayout_5.addWidget(self.pushButton_46, 0, 9, 1, 1)
        self.pushButton_158 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_158.setObjectName(_fromUtf8("pushButton_158"))
        self.gridLayout_5.addWidget(self.pushButton_158, 9, 3, 1, 1)
        self.pushButton_151 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_151.setObjectName(_fromUtf8("pushButton_151"))
        self.gridLayout_5.addWidget(self.pushButton_151, 8, 3, 1, 1)
        self.pushButton_150 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_150.setObjectName(_fromUtf8("pushButton_150"))
        self.gridLayout_5.addWidget(self.pushButton_150, 8, 4, 1, 1)
        self.pushButton_153 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_153.setObjectName(_fromUtf8("pushButton_153"))
        self.gridLayout_5.addWidget(self.pushButton_153, 8, 5, 1, 1)
        self.pushButton_155 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_155.setObjectName(_fromUtf8("pushButton_155"))
        self.gridLayout_5.addWidget(self.pushButton_155, 8, 2, 1, 1)
        self.pushButton_161 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_161.setObjectName(_fromUtf8("pushButton_161"))
        self.gridLayout_5.addWidget(self.pushButton_161, 9, 2, 1, 1)
        self.pushButton_149 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_149.setObjectName(_fromUtf8("pushButton_149"))
        self.gridLayout_5.addWidget(self.pushButton_149, 8, 6, 1, 1)
        self.pushButton_157 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_157.setObjectName(_fromUtf8("pushButton_157"))
        self.gridLayout_5.addWidget(self.pushButton_157, 8, 1, 1, 1)
        self.pushButton_164 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_164.setObjectName(_fromUtf8("pushButton_164"))
        self.gridLayout_5.addWidget(self.pushButton_164, 9, 4, 1, 1)
        self.pushButton_166 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_166.setObjectName(_fromUtf8("pushButton_166"))
        self.gridLayout_5.addWidget(self.pushButton_166, 9, 1, 1, 1)
        self.pushButton_165 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_165.setObjectName(_fromUtf8("pushButton_165"))
        self.gridLayout_5.addWidget(self.pushButton_165, 9, 5, 1, 1)
        self.pushButton_156 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_156.setObjectName(_fromUtf8("pushButton_156"))
        self.gridLayout_5.addWidget(self.pushButton_156, 8, 9, 1, 1)
        self.pushButton_154 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_154.setObjectName(_fromUtf8("pushButton_154"))
        self.gridLayout_5.addWidget(self.pushButton_154, 8, 8, 1, 1)
        self.pushButton_159 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_159.setObjectName(_fromUtf8("pushButton_159"))
        self.gridLayout_5.addWidget(self.pushButton_159, 9, 6, 1, 1)
        self.pushButton_162 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_162.setObjectName(_fromUtf8("pushButton_162"))
        self.gridLayout_5.addWidget(self.pushButton_162, 9, 7, 1, 1)
        self.pushButton_152 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_152.setObjectName(_fromUtf8("pushButton_152"))
        self.gridLayout_5.addWidget(self.pushButton_152, 8, 7, 1, 1)
        self.pushButton_160 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_160.setObjectName(_fromUtf8("pushButton_160"))
        self.gridLayout_5.addWidget(self.pushButton_160, 9, 8, 1, 1)
        self.pushButton_163 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_163.setObjectName(_fromUtf8("pushButton_163"))
        self.gridLayout_5.addWidget(self.pushButton_163, 9, 9, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_5, 1, 1, 1, 1)
        self.textEdit = QtGui.QTextEdit(self.gridLayoutWidget)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.gridLayout_7.addWidget(self.textEdit, 1, 0, 1, 1)
        self.reload_board = QtGui.QPushButton(self.gridLayoutWidget)
        self.reload_board.setMaximumSize(QtCore.QSize(995, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.reload_board.setFont(font)
        self.reload_board.setObjectName(_fromUtf8("reload_board"))
        self.gridLayout_7.addWidget(self.reload_board, 2, 1, 1, 1)
        self.execute_code = QtGui.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.execute_code.setFont(font)
        self.execute_code.setObjectName(_fromUtf8("execute_code"))
        self.gridLayout_7.addWidget(self.execute_code, 2, 0, 1, 1)
        self.label = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_7.addWidget(self.label, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_2 = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_7.addWidget(self.label_2, 0, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.gridLayoutWidget.raise_()
        self.pushButton_62.raise_()
        self.pushButton_46.raise_()
        self.gridLayoutWidget.raise_()
        self.textEdit.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.pushButton_31.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_21.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_22.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_25.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_23.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_26.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_24.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_27.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_30.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_28.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_29.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_34.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_32.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_33.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_35.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_37.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_38.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_36.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_39.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_40.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_130.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_77.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_76.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_127.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_79.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_129.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_78.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_128.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_126.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_132.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_133.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_135.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_131.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_138.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_136.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_137.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_61.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_56.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_66.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_51.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_143.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_144.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_146.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_148.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_147.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_140.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_71.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_75.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_72.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_145.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_74.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_73.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_141.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_142.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_42.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_54.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_49.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_55.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_48.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_45.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_53.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_41.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_44.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_52.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_43.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_59.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_64.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_63.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_68.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_67.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_50.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_47.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_69.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_58.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_57.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_65.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_60.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_70.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_139.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_134.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_62.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_46.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_158.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_151.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_150.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_153.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_155.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_161.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_149.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_157.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_164.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_166.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_165.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_156.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_154.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_159.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_162.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_152.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_160.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_163.setText(_translate("MainWindow", "PushButton", None))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.5pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">class program {</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">    program() {</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">        move()</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">    }</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">}</span></p></body></html>", None))
        self.reload_board.setText(_translate("MainWindow", "Reload Board", None))
        self.execute_code.setText(_translate("MainWindow", "Execute code", None))
        self.label.setText(_translate("MainWindow", "Karel code", None))
        self.label_2.setText(_translate("MainWindow", "Board", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

